### ISSUE TITLE
Docblock

### ISSUE THREAD

**Issue by vrgenl** [MehediDracula/PHP-Constructor#4]
Hi i've just installed PHP-Constructor because I was missing something like the phpcompanion so thumbs up for taking the time developing this extension.

I've noticed that when insert the params it is inserted between the __construct and the */

```
    protected $test;

    /**
     * Construct class
     */
    public function __construct($test)
    {
        $this->test = $test;
    }
```

```
    protected $test;

    /**
     * Construct class
     */
    protected $property;

    public function __construct($test, $property)
    {
        $this->test = $test;
        $this->property = $property;
    }
```

If you could find the time to resolve this issue you have a solid vscode extension.

**Comment by MehediDracula** [comment]
fixed on new version

**Comment by MehediDracula** [comment]
fixed on new version
