### ISSUE TITLE
Constructor visibility defaults to protected

### ISSUE THREAD

**Issue by bradykeeling** [MehediDracula/PHP-Constructor#9]
For some reason, the default constructor visibility is protected even though it's set to public.

![screen shot 2018-11-19 at 11 28 47 am](https://user-images.githubusercontent.com/3791996/48724306-7efc2e00-ebee-11e8-9f49-5b22b7133cdb.png)
![screen shot 2018-11-19 at 11 28 33 am](https://user-images.githubusercontent.com/3791996/48724307-7efc2e00-ebee-11e8-9d4a-b5ed66bb3f34.png)

Great extension overall!

**Comment by MehediDracula** [comment]
I'll look into it.

**Comment by markdegrootnl** [comment]
It seems to use the setting `phpConstructor.visibility` instead of `phpConstructor.constructorVisibility`.
